static const Rule rules[] = {
	/* xprop(1):
	 *	WM_CLASS(STRING) = instance, class
	 *	WM_NAME(STRING) = title
	 */
	/* class                                                  instance    title                   tags mask     iscentered     isfloating     monitor */
	{ "Gimp",                                                 NULL,       NULL,                   0,            1,             1,             -1 },
	{ "librewolf",                                            NULL,       NULL,                   0,            1,             0,             -1 },
	{ "librewolf",                                            "Devtools", NULL,                   0,            1,             1,             -1 },
	{ "librewolf",                                            "Browser",  NULL,                   0,            1,             1,             -1 },
	{ "librewolf",                                            "Toolkit",  NULL,                   0,            1,             1,             -1 },
	{ "Firefox",                                              NULL,       NULL,                   0,            1,             0,             -1 },
	{ "Firefox",                                              "Devtools", NULL,                   0,            1,             1,             -1 },
	{ "Firefox",                                              "Browser",  NULL,                   0,            1,             1,             -1 },
	{ "Firefox",                                              "Toolkit",  NULL,                   0,            1,             1,             -1 },
  { "Chromium",                                             NULL,       NULL,                   0,            1,             0,             -1 },
	{ "Discord",                                              NULL,       NULL,                   0,            1,             0,             -1 },
	{ "zoom",                                                 NULL,       NULL,                   0,            1,             1,             -1 },
//	{ "zoom",                                               NULL,       "Zoom Meeting",         0,            1,             0,             -1 },
//	{ "zoom",                                               NULL,       "Zoom - Free Account",  0,            1,             0,             -1 }, // Doesn't work. WIP.
	{ "qTox",                                                 NULL,       NULL,                   0,            1,             1,             -1 },
	{ "feh",                                                  NULL,       NULL,                   0,            1,             1,             -1 },
	{ "xdman-Main",                                           NULL,       NULL,                   0,            0,             1,             -1 },
	{ "mpv",                                                  NULL,       NULL,                   0,            1,             1,             -1 },
	{ "ffplay",                                               NULL,       NULL,                   0,            1,             1,             -1 },
	{ "io.github.celluloid_player.Celluloid",                 NULL,       NULL,                   0,            1,             1,             -1 },
	{ "davinci-resolve",                                      NULL,       NULL,                   0,            1,             1,             -1 },
	{ "Galculator",                                           NULL,       NULL,                   0,            1,             1,             -1 },
	{ "thunar",                                               NULL,       NULL,                   0,            1,             0,             -1 },
	{ "Zathura",                                              NULL,       NULL,                   0,            1,             0,             -1 },
	{ "Emacs",                                                NULL,       NULL,                   0,            1,             0,             -1 },
	{ "st",                                                   NULL,       NULL,                   0,            1,             0,             -1 },
	{ "scratchpad",                                           NULL,       NULL,                   0,            1,             1,             -1 },
	{ "eva",                                                  NULL,       NULL,                   0,            1,             1,             -1 },
	{ "btop",                                                 NULL,       NULL,                   0,            1,             1,             -1 },
	{ "btm",                                                  NULL,       NULL,                   0,            1,             1,             -1 },
	{ "ncmpcpp",                                              NULL,       NULL,                   0,            1,             1,             -1 },
	{ "Pavucontrol",                                          NULL,       NULL,                   0,            1,             1,             -1 },
	{ "qalculate-qt",                                         NULL,       NULL,                   0,            1,             1,             -1 },
	{ "Lxappearance",                                         NULL,       NULL,                   0,            1,             1,             -1 },
	{ "qt5ct",                                                NULL,       NULL,                   0,            1,             1,             -1 },
	{ "qt6ct",                                                NULL,       NULL,                   0,            1,             1,             -1 },
	{ "Kvantum Manager",                                      NULL,       NULL,                   0,            1,             1,             -1 },
	{ "Plank",                                                NULL,       NULL,                   0,            0,             1,             -1 },
	{ "kdeconnect.app",                                       NULL,       NULL,                   0,            1,             1,             -1 },
	{ "lxqt-config",                                          NULL,       NULL,                   0,            1,             1,             -1 },
	{ "Nm-connection-editor",                                 NULL,       NULL,                   0,            1,             1,             -1 },
	{ "Blueman-manager",                                      NULL,       NULL,                   0,            1,             1,             -1 },
};
