#!/bin/sh
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Keyboard
setxkbmap us &
xset r rate 225 45 &

# Audio Server
start_audio () {
    pipewire &
    wireplumber &
    pipewire-pulse &
    mpd &
}

start_audio &

# Dynamic Window Manager
#dbus-run-session dwm

# Sessions
session=${1:-dwm}

case $session in
  dwm       ) dbus-run-session dwm;;
  kde       ) export DESKTOP_SESSION=plasma && exec startplasma-x11;;
  kdeway    ) export DESKTOP_SESSION=plasma && exec startplasma-wayland;;
  *         ) exec $1;;
esac
